---
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-debian:bullseye"
  amd64: "ghcr.io/home-assistant/amd64-base-debian:bullseye"
  armhf: "ghcr.io/home-assistant/armhf-base-debian:bullseye"
  armv7: "ghcr.io/home-assistant/armv7-base-debian:bullseye"
  #i386: "ghcr.io/home-assistant/i386-base-debian:bullseye"
labels:
  org.opencontainers.image.authors: "Spiro C <spiroc@gmail.com>"
  org.opencontainers.image.title: "Home Assistant LedFX add-on"
  org.opencontainers.image.description: "A network based LED effect controller with support for advanced real-time audio effects!"
  org.opencontainers.image.source: "https://github.com/YeonV/home-assistant-addons/tree/master/ledfx-beta"
  org.opencontainers.image.licenses: "MIT"
